### ISSUE TITLE
Käyttäjänä haluan hakea kursseja niiden nimella ja/tai niiden kurssikoodilla esim "TKT110011"

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#102]
Hyväksymis kriteerit:
 
Kursseja voi hakea oman komponentin kautta ja ohjelma ehdottaa mahdollisia osumia tietokannasta löytyvien kurssien perusteella. Haku toimii kurssikoodien ja nimien perusteella. 

- [x] #32 
- [x] #134
- [x] #135 
- [x] #141
- [x] #142

**Comment by Janitus** [comment]
Cypresstestattu toiminnallisuuksia mm:

- Voi hakea kurssikoodilla
- Voi hakea kurssin nimellä
- Voi klikata kurssia ja nähdä tämän esitietovaatimukset
