### ISSUE TITLE
Käyttäjänä haluan nähdä popuppina ohjelmalta tärkeät viestit

### ISSUE THREAD

**Issue by Janitus** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#104]
- [x] #105 
- [x] #131
- [x] #132
- [x] #133

**Comment by Janitus** [comment]
- Viestit tulee olla lyhyitä ja kestää joitain sekunteja
- Viestit tulee olla järkevässä muodossa esim. ei JSON muotoista höttöä
- Viestit on oltava selkeästi luettavissa (esim. järkevä väriteema)
- Viesteistä on saatava hyvin selville, onko kyseessä virheviesti, onnistumisviesti tms. (Myös esim. väriteeman kautta)

**Comment by VehvilainenPooki** [comment]
Testien kirjoittaminen jäljellä

**Comment by Janitus** [comment]
Yksi cypress E2E testi toteutettu, jossa avataan tutkinto ja tarkastetaan ilmestyykö sieltä oikea viesti käyttäjälle.
