### ISSUE TITLE
Tietokantaan lista tutkinnoista ja niiden koodeista

### ISSUE THREAD

**Issue by VehvilainenPooki** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#106]
Tämän haun takaa tiedot tietokantaan [https://od.helsinki.fi/eduviewer/coded_educations](https://od.helsinki.fi/eduviewer/coded_educations)

**Comment by rpessi** [comment]
Sovelluksessa on siirretty käyttämään toista tutkintokoodia ja valikoima tutkintoja tallentuu degreeinfo-tauluun, kun sovellus käynnistetään ensimmäistä kertaa. Uusia tutkintoja on haluttaessa helppo lisätä json-tiedostoon. Drop-down-menussa ei ole tällä hetkellä hakua, joten kymmenien tutkintojen lisääminen ei ole muutenkaan vielä ajankohtaista.
