### ISSUE TITLE
Poisteaan kovakoodatut tiedot

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#115]

**Comment by Janitus** [comment]
Poistettu kovakoodatut kurssit backendistä, ja ainakin vielä on yhdet kovakoodatut setit jäljellä frontissa (se millä tiedoilla tutkinto haetaan!)

**Comment by VehvilainenPooki** [comment]
@Gudkat Poisti kovakoodatun tutkinnon haun ja valinnan. Nyt sivun avatessa lista tutkintoja haetaan, josta valitaan listan ensimmäinen. Lisäksi tutkintovalikko toimii oikein🤞
