### ISSUE TITLE
Poistetaan turhat console.log viestit

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#116]

**Comment by Janitus** [comment]
Joitain viestejä on tullut korvattua loggerilla, sekä myös siirretty frontin messagerille käyttäjälle nähtäväksi

**Comment by Janitus** [comment]
Timo korjasi kirjoitushetkellä kaikki consolelog viestit ja korvasi tärkeät oikeanlaisilla viesteillä
