### ISSUE TITLE
end to end testaus (optional)

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#117]

**Comment by Janitus** [comment]
Ensimmäiset E2E cypress testit ajettu projektiin sisälle. Nämä eivät kuitenkaan kuulu käsittääkseni osaksi CI/CD putkea! Localisti ajettavissa.

**Comment by Janitus** [comment]
Cypresstestejä lisää user messageille, degreelle sekä useampi search course barille.
