### ISSUE TITLE
Axios konffaus BaseURL

### ISSUE THREAD

**Issue by Gudkat** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#126]

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i want to worke on the issue if there is no one currenlty workeing on it just i need a little informations about the task

**Comment by Gudkat** [comment]
> Hi, i want to worke on the issue if there is no one currenlty workeing on it just i need a little informations about the task

Hey Amrani, 

Thanks for the interest in our project! This is a course project in University and with learning outcomes in mind we decided we want to do this ourselves.
