### ISSUE TITLE
Alert viesti tulee näkyviin

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#131]
Viestit näkyvät jonkin aikaa näytöllä ja katoavat

**Comment by Janitus** [comment]
Viesteille on annettu 8 sekunnin raja milloin ne näkyvät ennenkuin katoavat. Viesteille myös annettu pieni valkoinen kutistuva palkki joka ilmaisee tämän käyttäjälle.
