### ISSUE TITLE
Viesteille väri tms mistä saa selville minkälainen viesti

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#132]

**Comment by Janitus** [comment]
Viesteille on annettu kahdet värit, haalean sininen tavallisille infoviesteille, ja punainen virheviesteille. On myös mahdollista liittää jokaiseen viestiin jatkossa prefixinä vaikka "Info" tai "Error" joka ilmaisee tämän tarkemmin, mutta nyt on jätetty kehittäjän päätettäväksi mitä tarkalleen ottaen halutaan täällä viestiä.
