### ISSUE TITLE
Viestit tulevat järkevässä, arvokkaassa muodossa (esim. palvelimeen ei saa yhteyttä, eikä json mylly)

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#133]

**Comment by Janitus** [comment]
Viesti on nyt toteutettu tavallisella stringiparametrilla, joten jää kehittäjän päätettäväksi mitä sinne sisällytetään. Täten jääkööt kehittäjän vastuulle, mitä sinne syötetään? En sulje itse taskia kuitenkaan, mikäli tähän halutaan muutos.
