### ISSUE TITLE
Käyttäjänä haluan kattavat ohjeet ohjelman käyttämistä varten.

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#144]
- [x] #147
- [x] #148
- [x] #149

**Comment by VehvilainenPooki** [comment]
Ohjeet luotu: [https://github.com/Kurssiesitieto/kurssiesitieto-ohtuprojekti/blob/main/documentation/user-guide.md](https://github.com/Kurssiesitieto/kurssiesitieto-ohtuprojekti/blob/main/documentation/user-guide.md)
