### ISSUE TITLE
Andrei ja Pooki menee "juttelemaan" Toskan kanssa

### ISSUE THREAD

**Issue by Gudkat** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#146]

**Comment by VehvilainenPooki** [comment]
Luukkainen tavoitettu. Sovittu Torstaille tapaaminen. Kellonaika vielä päättämättä.

**Comment by VehvilainenPooki** [comment]
Tuotantoon vienti tapahtuu suunnitelmien mukaan 19.4. perjantaina klo. 12->. Minä ja Andrei mennään silloin katsomaan Luukkaisen ja OpenShift jumalan kanssa asia kuntoon.
