### ISSUE TITLE
Ohjeet tutkinnon lisäämiseen löytyvät Githubista.

### ISSUE THREAD

**Issue by Gudkat** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#147]

**Comment by Janitus** [comment]
Ohjeet on lisätty githubiin tutkinnon lisäämiselle

**Comment by Janitus** [comment]
Ohjeita paranneltu huomattavasti luomalla webbisivupohjainen vaihtoehto, sekä tälle visuaaliset ohjeet.
