### ISSUE TITLE
Ohjeet ohjelman käyttämistä varten ovat olemassa

### ISSUE THREAD

**Issue by Gudkat** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#148]

**Comment by Janitus** [comment]
Ohjeet on luotu githubiin, sisältäen tutkintovalikon käyttämisen, hakupalkin käyttämisen, sekä kurssikuvauksen luku. Myös ohjeet oman tutkinnon luontiin ovat toteutettu (jokseenkin mahdollisesti tämä ei täydellinen.)
