### ISSUE TITLE
HY tunnuksilla sovellukseen kirjautumisen implementointi

### ISSUE THREAD

**Issue by VehvilainenPooki** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#174]
Sovellus kulkee Shibboleth middlewaren läpi, joka mahdollistaa HY kirjautumisen. Nyt tulisi päättää miten kirjautuminen reititetään ja toteuttaa se.

Hyväksymiskriteerit:
- [x] kirjautumislinkki lisätty etusivulle
- [x] kirjautumiseen liittyvät testit toteutettu

Taskit:
- [x] #187 
- [x] #188 
- [x] #189 
- [x] #201
- [x] #202
- [x] #190
- [x] #224
- [x] #240
- [x] #241
- [x] #242
- [x] #243

**Comment by rpessi** [comment]
Hyväksymiskriteerit:
- [ ] ???
- [ ] ???
- [ ] ???

Taskit:
- [ ] Kirjautumiseen liittyvän koodin tutkiminen ja löydösten raportointi
- [ ] Kirjautumistoiminnon teknisen ratkaisun selvittely
- [ ] Kirjautumistoiminnon ohjelmointi
- [ ] Kirjautumistoiminnon testaus

**Comment by ShootingStar91** [comment]
Pingatkaa vaikka mua sitten vapaasti jos on jotain lisäkysymyksiä tuosta niin voin koittaa auttaa

**Comment by phuvio** [comment]
@ShootingStar91 Moi, sain lokaalisti toimimaan, mutta ei toiminut stagingilla. 
Kun apinoin Norpan koodia, niin lokaalisti alkoi toimia, mutta URL:stä hävisi esitieto-osuus. Lisäsin sitten ympäristömuuttujiksi: 
VITE_BASE_PATH=/esitieto
VITE_API_BASE_URL=http://localhost:3001/api
ja laitoin frontin puolelle basename Routeriin. Näillä sain lokaalisti toimimaan oikein, mutta ei tosiaan toimi, kun committaa stagingiin.

**Comment by ShootingStar91** [comment]
Kokeilin tuota stagingia network tabi auki. Ensimmäinen request toimii, mutta muut js-tiedostoja hakevat ei toimi. Niissä on se ero että urlissa on "url/esitieto/..". Eli tuo url näyttää menevän suoraan oikeaan osoitteeseen ilman esitieto-prefixiä - stagingilla siis. Varmaan jokin asetus openshiftissä reitittää sen siihen /esitieto/ urliin shibbolethiin, jolloin sitä esitieto-prefixiä ei tarvita stagingilla. Tuotannossahan voi olla eri asia, kun siellä se pitää olla siinä urlissa. Eli jollain ympäristömuuttujalla voit katsoa että ollaanko stagingilla, ja jos ollaan niin sitä esitieto-osaa ei tarvita.

**Comment by ShootingStar91** [comment]
Pitäisiköhän tuo suora route poistaa? Eli kun painat podia niin siitä löytyy "Route" jonka nimi on "kurssiesitieto-staging" joka menee suoraan sovellukseen ilman shibbolethia. Luultavasti ette tarvitse tuota enää, kannattaa poistaa

**Comment by phuvio** [comment]
Ehdin revertoida mun commitin, niin nyt se on mainin tilassa. Voin tietty committaa uudelleen. Siinä on julkinen puoli staging/esitieto/public ja kirjautumispuoli staging/esitieto/kirjauduttu

**Comment by ShootingStar91** [comment]
En oikein nyt hahmota mitä kaikkea koodissa oli ja miten se ei toiminut. Suosittelen askelia

- lisää loggaus niin että ennen mitään, jopa ennen tuota app.use(static...) kohtaa, backend console.logaa sisään tulleen urlin kokonaan niin että näät mitä tiedostoa/kansiota se etsii
- katso että dist kansio on oikein: jos ajetaan src-kansiosta niin se taitaa olla parent-kansion alla eli ../dist
- katso että shibbolethin conffi vastaa sitä miten oletat routejen käyttäytyvän
- katso network tabista mihin tarkalleen requestit menee ja mitä ne palauttaa. tällöin sen sijaan että sanot "ei toimi", voit sanoa "request feilaa urliin xxx palauttaen virheen yyy"

**Comment by phuvio** [comment]
Pahoittelut, revert sekoitti koodin. Nyt mainissa on tämän hetkinen koodi. Lisäsin console.loginin backendin terminaaliin. Se menee ymmärtääkseni OpenShiftiin, jonne en tänään pääse. 
Kun menee [ https://shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi/esitieto ]( https://shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi/esitieto ) niin sivu on tyhjä, mutta sillä on meidän määrittelemät värikoodit. Sivulle pitäisi tulla näkyviin yläpalkki ja sen alle laatikkokaavio valkoisella pohjalla.
Selaimen verkko-välilehdellä esitieto antaa URL https://shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi/esitieto ja koodin 200 OK. 
expressin static on nyt express.static(path.join(__dirname, '../dist'))
frontendissä lisäsin basename='"/esitieto" ja muutin linkit nyt import.meta.env.BASE_URL + "/", jonka pitäisi ymmärtääkseni vastata shibbolethin konfausta ja import.meta.env.BASE_URL + "/kirjauduttu", joista pelkkä /esitieto on tarkoitus olla avoin kaikille ja muille sivuille pääsee vain kirjautumalla.
Nyt en tiedä sotkeeko tuo basename ja import.meta.env.BASE_URL toisiaan. Vai onko ongelma sittenkin shibbolethin konfauksessa.
Kokeilin hakea myös suoraan tietoja tietokannasta esim. https://shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi/esitieto/api/getCourses joka näyttää toimivan oikein.

**Comment by ShootingStar91** [comment]
![image](https://github.com/Kurssiesitieto/kurssiesitieto-ohtuprojekti/assets/46905824/275b779f-df87-41ba-a3d8-3d311264a8d3)

Requesteissa tulee selvästi nuo js-tiedostot onnistuneesti fronttiin, tämä johdatti epäilemään että kyse on frontin viasta. Laitoin tuossa js-tiedostossa CTRL+F ja BASE_URL niin löytyi että se on "esitieto". Joten kun base url ja basename on molemmat käytössä ja molemmat on esitieto niin sovellus toimii tällä urlilla: https://shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi/esitieto/esitieto

**Comment by phuvio** [comment]
@ShootingStar91 Kiitos vinkistä. Poistin basenamen ja staging lähti toimimaan. Kirjautuminen ei vielä toimi, mutta johtuu varmaankin siitä, että /esitieto ja /esitieto/kirjauduttu pitää vaihtaa /esitieto/public ja /esitieto/kirjauduttu

**Comment by phuvio** [comment]
@ShootingStar91 Kiitos vielä jeesistä. Kirjautuminen lähti toimimaan. Onko uloskirjautumiselle valmista ohjetta tai linkkiä?

**Comment by ShootingStar91** [comment]
En tiedä, katsoisin miten on toteutettu niissä muissa projekteissa mitkä on samassa shibbolethissa

**Comment by phuvio** [comment]
@ShootingStar91 Hei, iloittiin liian aikaisin. Sovellus toimii oikein, kun on kirjautuneena sisään. Jos ei ole kirjautunut sisään ja yrittää avoimelle puolelle /esitieto/public, niin ei tule mitään näkyviin ja selaimen konsoliin tulee virheilmoitus: Access to script at 'https://login-test.it.helsinki.fi/idp/profile/SAML2/Redirect/SSO?SAMLRequest=nZLN...' (redirected from 'https://shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi/projekti/assets/index-DbJqAtw4.js') from origin 'https://shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Network-välilehdellä näyttää
- public antaa 304 Not Modified, joka sama kuin kirjautuneena
- index-BCCKidxZ.js 302 Found, kirjautuneena tulee 304
- index-BQ_E-71F.css 302 Found, kirjautuneenan 304

Kokeilin Shibbolethin configissa location-osia kaikissa järjestyksissä ja kokeilin ylempää projektin konfauksista kaikkia vaihtoehtoja. Sama lopputulos. Kokeilin vielä lisätä location-osiin:
Header always set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
Header always set Access-Control-Allow-Headers "Content-Type, Authorization"
mutta ei vaikutusta. 

Testasin myös toisen ryhmän urleja projekti/topics ja projekti/customer-review. Safarilla ylävalikko tuli näkyviin. Edgellä, Chromella ja Firefoxilla tuli tyhjä sivu ja samat virheilmoitukset konsoliin.

**Comment by ShootingStar91** [comment]
@phuvio 
Kokeiletteko suoraan tuota shibbolethin urlia? Luulisin että sitä kautta ei pidä mennä. Mulla tulee eri error jos menen https://kurssiesitieto-staging-ohtuprojekti-staging.apps.ocp-test-0.k8s.it.helsinki.fi/

**Comment by ShootingStar91** [comment]
Tai äh, sekoilin, unohda äskeinen.

**Comment by ShootingStar91** [comment]
@AleksTeresh do you know anything about this -  CORS-issue after trying to implement partial shibboleth setup

> @ShootingStar91 Hei, iloittiin liian aikaisin. Sovellus toimii oikein, kun on kirjautuneena sisään. Jos ei ole kirjautunut sisään ja yrittää avoimelle puolelle /esitieto/public, niin ei tule mitään näkyviin ja selaimen konsoliin tulee virheilmoitus: Access to script at 'https://login-test.it.helsinki.fi/idp/profile/SAML2/Redirect/SSO?SAMLRequest=nZLN...' (redirected from 'https://shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi/projekti/assets/index-DbJqAtw4.js') from origin 'https://shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Network-välilehdellä näyttää
> 
> * public antaa 304 Not Modified, joka sama kuin kirjautuneena
> * index-BCCKidxZ.js 302 Found, kirjautuneena tulee 304
> * index-BQ_E-71F.css 302 Found, kirjautuneenan 304
> 
> Kokeilin Shibbolethin configissa location-osia kaikissa järjestyksissä ja kokeilin ylempää projektin konfauksista kaikkia vaihtoehtoja. Sama lopputulos. Kokeilin vielä lisätä location-osiin: Header always set Access-Control-Allow-Origin "*" Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT" Header always set Access-Control-Allow-Headers "Content-Type, Authorization" mutta ei vaikutusta.
> 
> Testasin myös toisen ryhmän urleja projekti/topics ja projekti/customer-review. Safarilla ylävalikko tuli näkyviin. Edgellä, Chromella ja Firefoxilla tuli tyhjä sivu ja samat virheilmoitukset konsoliin.

**Comment by ShootingStar91** [comment]
@phuvio Oletteko edistyneet? Ollaan huomenna tavoitettavissa factoryllä tai zoomissa, niin voidaan koittaa debugata tätä.

**Comment by phuvio** [comment]
@ShootingStar91 Ei olla löydetty ratkaisua. Olen tämän viikon lomareissulla ja palaan ensi maanantaina. Sen jälkeen sillä 15. päivä alkavalla viikolla on hyvin aikaa selvittää tätä, jos teiltä löytyy aikaa.

**Comment by phuvio** [comment]
@ShootingStar91 Hei, onko teillä aikaa tällä viikolla. Voin tulla paikan päälle.

**Comment by ShootingStar91** [comment]
@phuvio Olen torstaina factoryllä, käykö silloin

**Comment by phuvio** [comment]
@ShootingStar91 Torstai sopii. Onko väliä mihin aikaan?

**Comment by ShootingStar91** [comment]
@phuvio vaikka 12-15 välillä olisi hyvä

**Comment by ShootingStar91** [comment]
@phuvio sittenkin 12.30 -15 välillä jos ok

**Comment by phuvio** [comment]
@ShootingStar91 Klo 12.30 sopii hyvin. Exactum taitaa olla nyt kiinni, niin miten pääsee sisälle?

**Comment by ShootingStar91** [comment]
Laitan sähköpostia

**Comment by ShootingStar91** [comment]
https://wiki.helsinki.fi/xwiki/bin/view/IAMasioita/Identiteetin-%20ja%20p%C3%A4%C3%A4synhallinnan%20dokumentaatio/Keskitetyn%20k%C3%A4ytt%C3%A4j%C3%A4tunnistuksen%20vaihtoehdot/1.%20Shibboleth%20%28SAML2%20%20OIDC%29/Ohjeet%20Shibbolointiin/

Kts. esim kohta "Attribuutit" jossa on linki "Shibbolethin käyttäjäattribuutit" jossa luettelo mahdollisista attribuuteista. 

Ja muitakin hyödyllisiä kohtia, tuossa on myös uloskirjautumisesta asiaa.

**Comment by phuvio** [comment]
@ShootingStar91  Hei, vielä yksi kysymys. Yritän saada sovelluksen toimimaan single page -tyyliin. Tavoitteena, että sovellus olisi kokonaan /esitieto-urlissa. Se toimisi sekä kirjautuneelle käyttäjällä että kirjautumattomalle käyttäjälle. Kokeilin Shibbolethissa configissa ensin laittaa /esitieto avoimeksi kaikille ja /esitieto/login kirjautumista vaativaksi. En saanut sitä toimimaan. Nyt /esitieto on avoin kaikille ja tein erillisen /esitietologin urlin, joka vaatii kirjautumisen. Tämä toimii oikein. Nyt en saa toimimaan /esitietologin-sivulta uudelleen ohjausta /esitieto-sivulle onnistuneen kirjautumisen jälkeen. 

En ole löytänyt tähän mitään ratkaisua, niin osaatko auttaa?

**Comment by ShootingStar91** [comment]
@phuvio mitä tarkemmin koitit ja miten se ei toiminut? Jos laitat "esitietologin"-routen palauttamaan frontin samalla tavalla kuin pelkkä esitieto-route, ja laitat vaikka sovelluksen juureen tarkistuksen että jos path on "esitietologin" niin se korvataan esitieto-routella. voisi olla esim useEffect hookissa. tai sitten komponentti joka renderöidään react-routerin kautta jos path on /esitietologin. en ole varma toimisiko tämä.

**Comment by ShootingStar91** [comment]
Luulen kylläkin että tähän pitäisi olla fiksumpi ratkaisu. Login-sivulle voisi ehkä redirectata suoraan ilman että "pakottaa" tuollaisen suojatun routen kautta. siihen oli joku url. Sitten jotenkin pitäisi saada se redirectaamaan takaisin sovellukseen, tähän on kai jotain metatietoja. voisi kysyä joltain

**Comment by ShootingStar91** [comment]
tuossa ohjesivulla jonka linkkasin aiemmin on kohta "Tukea ongelmiin". Siinä on yhteystietoja keneltä voisit kysellä miten login kannattaa toteuttaa
