### ISSUE TITLE
Käyttäjänä haluan hakea kurssin ja nähdä sen esitiedot kaaviona

### ISSUE THREAD

**Issue by VehvilainenPooki** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#20]
- [x] #31
- [x] #33
- [x] #34
- [x] #69

**Comment by Janitus** [comment]
Toiminnallisuus on toteutettu ja user testattu localissa. Tämä pitää vielä varmistaa, että openshiftin tietokanta pelaa odotetusti, niin tämän voi sitten merkkailla doneksi.
