### ISSUE TITLE
Kehittäjänä haluan hallinnoida sivuja sisäänkirjautumisen yhteydessä

### ISSUE THREAD

**Issue by sampsaoinonen** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#245]
Hyväksymiskriteerit

- [x] Tutkivalla testaamisella toimivaksi todettu

Taskit

- [x] #247
- [x] #248
- [x] #249
- [x] #274
- [x] #275
- [x] #276
- [x] #271
- [x] #272
- [x] #273
- [x] #277

**Comment by phuvio** [comment]
@ShootingStar91 Hei, joudun vielä kysymään neuvoa. Yritän saada Shibbolethista käyttäjän tietoja, jotta sivulla voidaan näyttää eri asioita riippuen onko käyttäjä kirjautunut vai ei. Asetin Shibbolethissa ShibUseHeaders On ja katsoin, että middleware toimii kuten Yliopiston shibboleth-postgres-example sivun middleware https://github.com/UniversityOfHelsinkiCS/shibboleth-postgres-example/blob/main/src/server/middleware/user.ts  Lisäsin meidän middlewareen testejä ja default-arvoja, että myös kirjautumaton käyttäjä toimii. Otin user middlewaresta autentikointitestit väliaikaisesti pois käytöstä, että näkyisi kaikissa tilanteissa mitä tietoja Shibbolethilta saadaan. Tulostin konsoliin käyttäjän tiedot ja onko kirjautunut vai ei. Lokaalisti tieto kulkee frontille. Mutta stagingillä konsoli näyttää käyttäjän kohdalle: email: "(null)", iamGroups: [], id: null, isAdmin: false, language: null, username: "(null)" eli näyttäisi, että Shibbolethilta ei tule tietoa tai sovellus ei osaa sitä lukea.

Yritin testata Postmanilla mitä tietoja Shibbolethilta tulee, mutta en ole saanut sillä autentikointia toimimaan, että olisin nähnyt mitä Shibboleth palauttaa. Nyt en oikein ymmärrä, onko vika Shibbolethin asetuksissa vai sittenkin sovelluksen puolella.

**Comment by ShootingStar91** [comment]
Logititko kaikki headerit? kannattaa logittaa se koko objekti eikä niitä headereita mitkä olettaa olevan siellä.

Katsoin rekisteristä joka hallinnoi tuota shibbolethia ja sinne pitäisi tulla nämä:
```
employeeNumber	
givenName	
hyPersonSisuId	
hyPersonStudentId	
mail	
schacPersonalUniqueCode	
sn	
uid	
```

tietysti vaatii myös että käyttäjälle on ne määritetty. mikä on testikäyttäjä millä yritit, voin katsoa rekisteristä mitkä tiedot sille on määritelty.

**Comment by phuvio** [comment]
Logitin koko objektin frontin puolella. Testikäyttäjänä on käyttäjänimi esitieto, jolla pitäisi olla vain uid ja mail. Niiden kohdalla tulee "(null)", muut antavat default arvon. Lisäsin vielä unfuck-utf8-headers-middleware, joka oli tuolla esimerkkitoteutuksessa mukana, mutta ei vaikutusta.

**Comment by ShootingStar91** [comment]
Koko objekti frontin puolella on varmaankin vain ne kentät, jotka on middlewaressa poimittu mukaan headers-objektista? Tarkoitan että lokittaisit koko headers objektin eli tuossa usermiddlewaressa console.log(req.headers) ja katso backendin logeista mitä se tulostaa

**Comment by ShootingStar91** [comment]
Mutta kieltämättä sillä pitäisi kuitenkin se mail olla. Asetin tuolle testikäyttäjälle lisää tietoja:

![image](https://github.com/user-attachments/assets/d976263d-3e76-4d94-8381-a236630729de)

**Comment by phuvio** [comment]
@ShootingStar91  Lisäsin lokin user middlewareen ja pushasin Gitiin, mutta mistä näen stagingin puolella backendin logit?

**Comment by ShootingStar91** [comment]
Openshiftistä. Paina podista ja linkki logs

**Comment by phuvio** [comment]
@ShootingStar91 Jostain syystä headereissa ei tule käyttäjän tietoja. 

Jos määrittelee erikseen
    RequestHeader set X-Uid "%{uid}"
    RequestHeader set X-Mail "%{mail}"

niin headereiden mukana tulee: 
  'x-forwarded-for': '128.214.138.138, 10.15.2.1',
  uid: '(null)',
  mail: '(null)',


Jos on pelkästään:
    ShibUseHeaders On

niin headereissa ei tosiaan tule käyttäjän tietoja:
  host: 'shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi',
  'sec-ch-ua': '"Not)A;Brand";v="99", "Google Chrome";v="127", "Chromium";v="127"',
  accept: 'application/json, text/plain, */*',
  'sec-purpose': 'prefetch;prerender',
  'sec-ch-ua-mobile': '?0',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
  'sec-ch-ua-platform': '"macOS"',
  purpose: 'prefetch',
  'sec-fetch-site': 'same-origin',
  'sec-fetch-mode': 'cors',
  'sec-fetch-dest': 'empty',
  referer: 'https://shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi/esitieto/start',
  'accept-encoding': 'gzip, deflate, br, zstd',
  'accept-language': 'fi-FI,fi;q=0.9,en-US;q=0.8,en;q=0.7',
  cookie: '_gcl_au=1.1.2122994308.1717413171; _fbp=fb.1.1717413171203.580071402; _hjSessionUser_735056=eyJpZCI6IjZlYTdhNzU0LWRhZTktNTc2My1hYjhiLTI3NGNkNDUwZTMyYSIsImNyZWF0ZWQiOjE3MTc0MTMxNzEzNDIsImV4aXN0aW5nIjp0cnVlfQ==; OBAR_LANG=en',
  'if-none-match': 'W/"77-bjEpE5fzvPjBN5n06tTzT11E1FE"',
  'x-forwarded-host': 'shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi, shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi',
  'x-forwarded-port': '443',
  'x-forwarded-proto': 'https',
  forwarded: 'for=193.166.130.233;host=shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi;proto=https',
  'x-forwarded-for': '193.166.130.233, 10.15.2.1',
  'x-forwarded-server': 'shibboleth.ext.ocp-test-0.k8s.it.helsinki.fi',
  connection: 'Keep-Alive'

**Comment by phuvio** [comment]
@ShootingStar91 Hei, meillä on vielä ongelmia saada Shibbolethista käyttäjän tiedot sovellukselle. Nyt alkaa ideat loppumaan, mutta olisi hyvä saada sovellus toimimaan ennen projektin loppua eli tämän kuun loppua. Olisiko mahdollista tulla käymään siellä teillä, niin voitaisiin katsoa missä vika. Meille sopisi:
- ti 20.8. klo 15->
- ke 21.8. klo 15->
- to 22.8. klo 15-> (tällöin en itse pääse, mutta muita pääsee paikalle)
Onnistuisiko joku näistä ajoista?

**Comment by ShootingStar91** [comment]
@phuvio 
Minulla ei ole nyt aikaa tuota katsoa, @mluukkai lupasi koittaa auttaa eli kyselkää häneltä

**Comment by phuvio** [comment]
@mluukkai
Hei, 
olemme saaneet sisäänkirjautumisen toimimaan. Ongelma on siinä, että vaikka homma toimii lokaalisti mock käyttäjällä, niin stagingillä Shibbolethilta ei tule käyttäjän tietoja. Olen katsonut muiden projektien konfauksia ja toteutuksia enkä ole löytänyt mitään merkittäviä eroja. Oma epäilykseni on, että OpenShiftin tai Shibbolethin konfauksessa on nyt joku juttu, minkä takia tiedot eivät lähde. 
Itse ehtisin yliopistolle
ti 20.8. klo 15->
ke 21.8. klo 15->
to 22.8. klo 15-> (tällöin en itse pääse, mutta muita pääsee paikalle)
