### ISSUE TITLE
Kun kurssia klikataan, kurssin kuvaus tulee näkyville sivupalkissa.

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#26]

**Comment by Gudkat** [comment]
Sivupalkissa kuvauksesta ei tullut siisti (liikaa tekstiä), mutta nyt siellä on nappi millä saa popup kuvauksen.

**Comment by VehvilainenPooki** [comment]
Tällä hetkellä Kandin tutkintoa klikatessa tulee joku virhe kori datan prosessoinnissa, jonka vuoksi ei näy kurssin opintopisteistä ja groupID:tä.
