### ISSUE TITLE
Tietokannasta voidaan etsiä kurssit tutkinnon mukaan

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#28]

**Comment by VehvilainenPooki** [comment]
Tällä commitilla suoritettu: https://github.com/Kurssiesitieto/kurssiesitieto-ohtuprojekti/commit/68ef81166e7b0795bdf292057ab866059c2fed3c

Helsinki.fi  rajapinta, joka palauttaa degreeStructure() funktiolla kurssin rakenteen, josta löytyy tutkintoon sisältyvät kurssit.
