### ISSUE TITLE
(Backend) Haetun kurssin esitietovaatimukset etsitään "rekursiivisesti"

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#33]

**Comment by Janitus** [comment]
Toteutus pilkottu pienemmäksi, jotta tämän voi merkata doneks. Uudessa issuessa pitää muokata, että hakee tieton tietokannan kautta eikä käytä väliaikaista dataa.

**Comment by Janitus** [comment]
Toteutus pilkottu pienemmäksi, jotta tämän voi merkata doneks. Uudessa issuessa pitää muokata, että hakee tieton tietokannan kautta eikä käytä väliaikaista dataa.
