### ISSUE TITLE
Kurssikaavio

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#4]

**Comment by Janitus** [comment]
Kurssikaavio on toiminnassa, sekä yhteydessä backendiin. Muutamia perustoimintoja lisättiin valmiiksi tietokantoja varten (lisää/poista), ja on myös viety backendiin. Myös UX toiminnallisuuksia lisättiin kaavioon mukaan (esim. autolayout)
