### ISSUE TITLE
Suodatin tutkintorakenteen sisällölle, jotta saa moduulit mahdollisimman järkevästi ulos

### ISSUE THREAD

**Issue by Janitus** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#59]

**Comment by Janitus** [comment]
Jonkinlainen suodatintoiminnallisuus on nyt, mutta ei hyvä sellainen.

**Comment by Owlaboy** [comment]
Tätä taskia ei tulla toteuttamaan, koska emme aio käyttä automaattista importointia.
