### ISSUE TITLE
Tietokannan rakenteen päivitys tukemaan nykyista ohjelman tilaa.

### ISSUE THREAD

**Issue by Gudkat** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#87]
Muokataan tietokantarakenne tukemaan kurssien ja tutkintojen tallentamista omaan tietokantaan sen sijaan, että yritetään hakea ne aina sisun rajapinnasta.

**Comment by Janitus** [comment]
Tietokanta on nyt uudistettu ja viety ohjelmaan, kurssit näkyvät frontendissä oikein. Datassa kuitenkin mahdollisesti jotain häikkää, ellei kyseessä ole käyttäjävirhe.
