### ISSUE TITLE
Käyttäjänä haluan työkalun opintosuunnitelman luomiseen.

### ISSUE THREAD

**Issue by Owlaboy** [Kurssiesitieto/kurssiesitieto-ohtuprojekti#96]
Hyväksymiskriteerit

- [x] Toiminnallisuudet testattu

Taskit

- [x] #259
- [x] #258
- [x] #257
- [x] #256
- [x] #255
- [x] #253
- [x] #252
- [x] #251
- [x] #262
- [x] #270
- [x] #263
- [x] #264
- [x] #265
- [x] #268
- [x] #269

**Comment by sampsaoinonen** [comment]
Ohjelmassa olisi uusi sivu jossa käyttäjät pystyisivät rakentamaan uusia tutkintokuvaajia.

- Mahdollisesti jaettuna kahteen osaan. Toisella puolella "koodista" rakennettu kuvaaja ja toisella puolella "koodin" muokkaaja.
